### PR TITLE
Basic CI Workflow in GitHub Actions

### LINKED ISSUE #32: Create a Workflow for branches, build and deployments
**As a** developer,
**I want to** put a workflow in place
**so that** I can manage the project more effectively 

**Acceptance Criteria:**

- In the actions tab create a custom/predefined workflow 
- build a pipeline
- create and manage branches
- do code and quality checks 
- add artifacts(optional)

**Estimated Time:**  TBD

### PR DESCRIPTION
**Pull request by borisliao**
This PR adds integration tests using pytest. In addition, a GitHub Actions workflow is also added to run pytest integration tests.

### CODE REVIEW

**Review by Exsects — DISMISSED** [review]

**Review by Exsects — DISMISSED** [review]

**Review by Exsects — APPROVED** [review]

**Comment by Karan-Jain** [comment]
Are we planning on doing integration tests  with pytests as well?

**Comment by Karan-Jain** [comment]
A gherkin format would work best

**Comment by borisliao** [comment]
> A gherkin format would work best

I looked in to the frameworks like Behave, and pytest-bdd which both support [Gherkin](https://en.wikipedia.org/wiki/Cucumber_(software)#Gherkin_language). I just don't understand the need to write our features and integration tests in to a gherkin style language when the collaborators are all developers.

**Comment by Karan-Jain** [comment]
Its not just for buisness. Gherkin helps organize the integration tests by keeping the feature(Scenarios) and the stepdef(code) seperate. This way we get a clear idea of what we are trying to test.

**Comment by borisliao** [comment]
I see, what I'm seeing now is maintaining a gherkin features file is more work then just making the test files with comments, especially when all our collaborators are developers, not QA, or business. Does it provide advantages with living documentation?

**Review by Karan-Jain — APPROVED** [review]

**Comment by borisliao** [comment]
#83 Will transition to Gherkin.

**Pull request merged**
