### PR TITLE
Integrate Database with Code

### PR DESCRIPTION
**Pull request by borisliao**
**Changes**

- New StateManager cog to share data between cogs
- /register slash command adds a record to the database
- Last but not least... code integration with the database
- Removed Crypto Auth

**TO DO in the future**

- Delete player after player has been stopped in the state manager
- delete entry in the config_db after bot leaves the guild #139 
- consider moving /register command operations to another place. was not moved in this branch due to MusicBoxContext not having the correct fields.
- Fix MusicBoxContext not having the correct fields.
- Clear to integrate webbooks after this PR.
- Add back admin channel

**Changes include**

- [x] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [x] Refactor (non-breaking/breaking change that refactor the previous code base)

**Todos**

- [ ] Updated and Passed Tests
- [ ] Passed Quality Checks
- [ ] Updated  Documentation

### CODE REVIEW

**Review by Karan-Jain — APPROVED** [review]

**Review by Karan-Jain — CHANGES_REQUESTED** [review]
Have a further discussion on StateManager

**Review by AvJain — COMMENTED** [review]
Needs more discussion on some components that were changed

**Review by Karan-Jain — APPROVED** [review]

**Comment by Exsects** [comment]
- Rename Record?
- Make dataclass immutable https://stackoverflow.com/questions/66194804/what-does-frozen-mean-for-dataclasses
- Put a limit for cache in the future (Need to create ticket)
- https://github.com/spulec/moto (Add database mocking for test )
- TypedDict vs dataclass
- Make unit tests test only one part at a time
- Remove database abstract class
- Remove dict_factory
- Have a further discussion for StateManager

**Comment by borisliao** [comment]
All team issues have been created in to issues, Tagged with [milestone](https://github.com/mbox-contributors/mbox/milestone/3). 

As discussed in the meeting, merging to the DB PR as to not delay work.

**Pull request merged**
